name: CommandSpy
main: tim03we\CommandSpy\Main
version: 1.0.0
api: 3.0.0
author: tim03we
description: Spioniere die Befehle anderer Spieler aus

commands:
  commandspy:
    description: Enter Spy-Mode
    aliases: ["cspy"]
permissions:
   commandspy.cmd:
    default: op
